"""LLM client abstraction.

Supports a mock provider (rule-based, fully offline) and an OpenAI-compatible
provider. The provider is selected via DATAWHISPER_LLM_PROVIDER env var.
"""
from __future__ import annotations

import json
import re
from typing import Any, Protocol

from .config import settings


class LLMClient(Protocol):
    def chat(self, system: str, user: str, *, json_mode: bool = False) -> str: ...


class MockLLMClient:
    """A deterministic, rule-based 'LLM' used so the app can run without keys.

    It is intentionally simple but produces structured JSON for the planner,
    SQL generator, and insight engine, allowing the full pipeline to function.
    """

    def chat(self, system: str, user: str, *, json_mode: bool = False) -> str:
        s = system.upper()
        if "PLANNER" in s:
            return self._plan(user)
        if "SQL" in s and "SCHEMA" in s:
            return self._sql(user)
        if "INSIGHT" in s or "EXPLAIN" in s:
            return self._insight(user)
        if "FOLLOWUP" in s or "SUGGEST" in s:
            return self._followups(user)
        if "PLAN" in s:
            return self._plan(user)
        return ""

    @staticmethod
    def _extract_json_block(text: str) -> str:
        m = re.search(r"```(?:json)?\s*(\{.*?\}|\[.*?\])\s*```", text, re.S)
        return m.group(1) if m else text.strip()

    @staticmethod
    def _plan(question: str) -> str:
        q = question.lower()
        steps = []
        if "vs" in q or "compare" in q or "versus" in q:
            steps = [
                {"id": 1, "action": "Fetch current period metric", "description": "Aggregate the primary measure for the current period grouped by the requested dimension."},
                {"id": 2, "action": "Fetch comparison period metric", "description": "Aggregate the same measure for the prior period grouped by the same dimension."},
                {"id": 3, "action": "Merge results", "description": "Join the two period aggregates on the dimension key."},
                {"id": 4, "action": "Calculate delta", "description": "Compute absolute change and percent change between periods."},
                {"id": 5, "action": "Rank", "description": "Order the results by the magnitude of change."},
                {"id": 6, "action": "Generate chart", "description": "Return grouped bar chart comparing the two periods."},
            ]
        elif "top" in q or "ranking" in q or "rank" in q:
            steps = [
                {"id": 1, "action": "Aggregate measure", "description": "Sum/avg the requested measure grouped by the dimension."},
                {"id": 2, "action": "Rank", "description": "Order descending and limit to the top N rows."},
                {"id": 3, "action": "Generate chart", "description": "Return a horizontal bar chart of the top entries."},
            ]
        elif "by" in q:
            steps = [
                {"id": 1, "action": "Aggregate measure", "description": "Aggregate the requested measure grouped by the requested dimension."},
                {"id": 2, "action": "Order", "description": "Order results appropriately (e.g. by date or by measure)."},
                {"id": 3, "action": "Generate chart", "description": "Return the appropriate chart type based on the dimension kind (time -> line, category -> bar)."},
            ]
        else:
            steps = [
                {"id": 1, "action": "Aggregate measure", "description": "Compute the requested single aggregate metric."},
                {"id": 2, "action": "Generate result", "description": "Return the scalar value with a formatted summary."},
            ]
        return json.dumps({"steps": steps})

    @staticmethod
    def _sql(user: str) -> str:
        # The actual SQL is generated by the SQL generator module which uses
        # schema metadata; the mock LLM is only a fallback. We return an empty
        # string so callers fall back to the rule-based generator.
        return ""

    @staticmethod
    def _insight(user: str) -> str:
        # Try to pull embedded JSON results string passed by the insight engine.
        try:
            payload = json.loads(user)
            rows = payload.get("rows", [])
            measure = payload.get("measure", "value")
            dimension = payload.get("dimension")
            summary = payload.get("summary", [])
            if not rows:
                return "No data was returned for this question."
            parts = []
            if summary:
                tot = summary.get("total")
                if tot is not None:
                    parts.append(f"Total {measure}: {tot}.")
                mx = summary.get("max")
                mn = summary.get("min")
                if mx is not None and mn is not None:
                    parts.append(f"Highest: {mx}; lowest: {mn}.")
            if dimension and rows:
                top = rows[0]
                parts.append(f"The leading {dimension} is {top.get('label', '?')}.")
            return " ".join(parts)
        except Exception:
            return "Here are the results for your question."

    @staticmethod
    def _followups(user: str) -> str:
        try:
            payload = json.loads(user)
            dim = payload.get("dimension")
            measure = payload.get("measure")
            suggestions = []
            if dim:
                suggestions.append(f"Break down {measure} by another dimension")
                suggestions.append(f"Compare {measure} across periods")
            suggestions.append(f"What are the top {measure} entries?")
            suggestions.append(f"Forecast {measure} for next period")
            suggestions.append("Show anomalies in the data")
            return json.dumps({"suggestions": suggestions[:4]})
        except Exception:
            return json.dumps({"suggestions": ["Show breakdown by another dimension", "Compare across periods", "Top entries", "Forecast next period"]})


class OpenAICompatibleClient:
    """An OpenAI-compatible chat client (works with OpenAI and many proxies)."""

    def __init__(self) -> None:
        import httpx  # local import
        self._http = httpx.Client(timeout=settings.query_timeout_seconds * 2)
        self._base = settings.openai_base_url.rstrip("/")
        self._key = settings.openai_api_key
        self._model = settings.openai_model

    def chat(self, system: str, user: str, *, json_mode: bool = False) -> str:
        resp = self._http.post(
            f"{self._base}/chat/completions",
            headers={"Authorization": f"Bearer {self._key}", "Content-Type": "application/json"},
            json={
                "model": self._model,
                "messages": [{"role": "system", "content": system}, {"role": "user", "content": user}],
                "temperature": 0.0,
                "response_format": {"type": "json_object"} if json_mode else None,
            },
        )
        resp.raise_for_status()
        return resp.json()["choices"][0]["message"]["content"]


_client: LLMClient | None = None


def get_llm() -> LLMClient:
    global _client
    if _client is None:
        if settings.llm_provider == "openai" and settings.openai_api_key:
            _client = OpenAICompatibleClient()
        else:
            _client = MockLLMClient()
    return _client
