"""The core analytics engine: intent detection, planner, SQL generator,
validator, self-correction loop, execution.

When a real LLM is configured (DATAWHISPER_LLM_PROVIDER=openai), the SQL is
generated by the model. Otherwise a deterministic rule-based generator uses the
parsed schema and the question to synthesize safe, read-only SQL.
"""
from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import Any

from .datasource import BaseConnector, TableSchema
from .llm import get_llm
from .schema_understanding import schema_to_text


@dataclass
class ParsedIntent:
    measure: str | None = None
    dimension: str | None = None
    date_filter: str | None = None
    compare: bool = False
    top_n: int | None = None
    table: str | None = None
    target_column: str | None = None
    raw: str = ""


@dataclass
class StepResult:
    step_id: int
    description: str
    sql: str | None = None
    rows: list[dict] = field(default_factory=list)
    error: str | None = None
    execution_time: float = 0.0


@dataclass
class AnalysisResult:
    intent: ParsedIntent
    plan: list[dict]
    steps: list[StepResult]
    final_rows: list[dict]
    sql: str
    execution_time: float
    retries: int = 0
    success: bool = True
    error: str | None = None


# ---------- intent detection ----------

AGG_WORDS = {"sum", "total", "revenue", "count", "avg", "average", "churn", "sales", "amount", "cost"}
COMPARE_WORDS = ("vs", "versus", "compare", "compared")
TOP_RE = re.compile(r"top\s+(\d+)", re.I)
LAST_N_RE = re.compile(r"last\s+(\d+)\s+(day|week|month|quarter|year)s?", re.I)
THIS_MONTH_RE = re.compile(r"this\s+(month|quarter|year)", re.I)
LAST_MONTH_RE = re.compile(r"last\s+(month|quarter|year)", re.I)
BY_RE = re.compile(r"\bby\s+(\w+(?:\s+\w+)?)", re.I)


def _resolve_column(name: str, schema: dict[str, TableSchema], kind_hint: str | None = None) -> tuple[str, str] | None:
    """Find (table, column) matching a name hint. Respect kind_hint strictly."""
    cand = name.strip().lower().replace(" ", "_").rstrip("s")
    candidates = []
    exact = []
    for tname, t in schema.items():
        for col in t.columns:
            col_l = col.name.lower()
            is_exact = (col_l == cand or col_l == cand + "s" or cand == col_l.rstrip("s") or cand + "s" == col_l)
            if is_exact:
                if kind_hint and col.kind != kind_hint:
                    continue
                exact.append((tname, col.name))
                continue
            if cand in col_l or col_l in cand:
                if kind_hint and col.kind != kind_hint:
                    continue
                candidates.append((tname, col.name))
    if exact:
        return exact[0]
    if candidates:
        return candidates[0]
    return None


TOP_WORD_RE = re.compile(r"\btop\s+(\d+\s+)?([a-z_]+)", re.I)


def _resolve_top_word(question: str, schema: dict[str, TableSchema], kind_hint: str | None = None) -> tuple[str, str] | None:
    """Extract the noun after 'top' (e.g. 'regions' from 'Top regions by revenue') and resolve it."""
    m = TOP_WORD_RE.search(question)
    if m:
        word = m.group(2).strip()
        return _resolve_column(word, schema, kind_hint)
    return None


def detect_intent(question: str, schema: dict[str, TableSchema]) -> ParsedIntent:
    q = question.lower()
    intent = ParsedIntent(raw=question)

    # Compare
    if any(w in q for w in COMPARE_WORDS):
        intent.compare = True

    # Top N
    m = TOP_RE.search(q)
    if m:
        intent.top_n = int(m.group(1))
    elif re.search(r"\btop\b", q):
        intent.top_n = 10  # default when "top X by Y" has no explicit count

    # Date filter
    if (mm := LAST_N_RE.search(q)):
        intent.date_filter = f"last_{mm.group(1)}_{mm.group(2)}"
    elif THIS_MONTH_RE.search(q):
        u = THIS_MONTH_RE.search(q).group(1)
        intent.date_filter = f"this_{u}"
    elif LAST_MONTH_RE.search(q):
        u = LAST_MONTH_RE.search(q).group(1)
        intent.date_filter = f"last_{u}"

    # Dimension (the first "by X")
    if (mm := BY_RE.search(q)):
        dim_word = mm.group(1).strip()
        if dim_word.lower() in ("month", "week", "year", "day", "quarter"):
            # time-based dimension; find a temporal column to group by truncation
            for tname, t in schema.items():
                for col in t.columns:
                    if col.kind == "temporal":
                        intent.dimension = f"time:{tname}.{col.name}:{dim_word}"
                        break
                if intent.dimension:
                    break
        else:
            resolved = _resolve_column(dim_word, schema, "categorical")
            if resolved:
                intent.dimension = f"{resolved[0]}.{resolved[1]}"
            elif intent.top_n and re.search(r"\btop\b", q):
                # "top X by Y" where Y is the measure: the dimension is X (the
                # noun immediately after "top").
                cand = _resolve_top_word(q, schema, "categorical")
                if cand:
                    intent.dimension = f"{cand[0]}.{cand[1]}"
    elif intent.top_n and re.search(r"\btop\b", q):
        # "Top regions" (no "by"): the word after "top" is the dimension.
        cand = _resolve_top_word(q, schema, "categorical")
        if cand:
            intent.dimension = f"{cand[0]}.{cand[1]}"

    # Measure: pick a numeric column whose name appears, else the first numeric col.
    tokens = set(re.findall(r"[a-z_]+", q))
    best = None
    for tname, t in schema.items():
        for col in t.columns:
            if col.kind == "numeric":
                if col.name.lower().rstrip("s") in tokens or any(tok in col.name.lower() for tok in tokens):
                    best = (tname, col.name)
                    break
        if best:
            break

    # Time-series fallback: if the question implies a trend ("over time",
    # "trend", "by month/week/...", "per day/...", "timeline") but no dimension
    # was chosen, default to a temporal grouping.
    TIME_TREND = ("over time", "trend", "timeline", "per day", "per month",
                  "per week", "per quarter", "per year", "by day", "by month",
                  "by week", "by quarter", "by year")
    if not intent.dimension and any(t in q for t in TIME_TREND):
        for tname, t in schema.items():
            for col in t.columns:
                if col.kind == "temporal":
                    grain = "month"
                    for g in ("day", "week", "quarter", "year"):
                        if g in q:
                            grain = g
                            break
                    intent.dimension = f"time:{tname}.{col.name}:{grain}"
                    break
            if intent.dimension:
                break
    if best:
        intent.table, intent.target_column = best
        intent.measure = f"{best[0]}.{best[1]}"
    else:
        # fallback: first numeric column anywhere
        for tname, t in schema.items():
            for col in t.columns:
                if col.kind == "numeric":
                    intent.measure = f"{tname}.{col.name}"
                    intent.table = tname
                    intent.target_column = col.name
                    break
            if intent.measure:
                break

    return intent


# ---------- planner ----------

def build_plan(question: str, intent: ParsedIntent) -> list[dict]:
    if intent.compare:
        return [
            {"id": 1, "action": "Fetch current period metric", "description": f"Aggregate {intent.measure} for the current period grouped by {intent.dimension}."},
            {"id": 2, "action": "Fetch comparison period metric", "description": f"Aggregate {intent.measure} for the prior period grouped by {intent.dimension}."},
            {"id": 3, "action": "Merge results", "description": "Join period aggregates on the dimension key."},
            {"id": 4, "action": "Calculate delta", "description": "Absolute and percent change."},
            {"id": 5, "action": "Rank", "description": "Order by magnitude of change."},
            {"id": 6, "action": "Generate chart", "description": "Grouped bar chart comparing periods."},
        ]
    steps = [{"id": 1, "action": "Aggregate", "description": f"Aggregate {intent.measure} grouped by {intent.dimension}."}]
    if intent.top_n:
        steps.append({"id": 2, "action": "Rank", "description": f"Order and limit to top {intent.top_n}."})
    steps.append({"id": len(steps) + 1, "action": "Generate chart", "description": "Select appropriate chart type."})
    return steps


# ---------- SQL generation ----------

def _trunc_expr(time_ref: str, grain: str) -> str:
    """Parse a dimension spec and return a DATE_TRUNC expression.

    Accepted formats:
      - "time:table.col:grain"  (the canonical format emitted by detect_intent)
      - "table.col"
    """
    table: str | None = None
    col: str | None = None
    if TimeDIM_RE.match(time_ref):
        # "time:orders.order_date:month"
        parts = time_ref.split(":")
        table, col = parts[1].split(".", 1)
    elif "." in time_ref:
        table, col = time_ref.split(".", 1)
    else:
        raise ValueError(f"Cannot parse time dimension spec: {time_ref!r}")
    g = grain.lower() if grain else "month"
    return f'DATE_TRUNC(\'{g}\', "{table}"."{col}")'


TimeDIM_RE = re.compile(r"^[a-z_]+:[a-z_]+\.[a-z_]+:[a-z_]+$")


def _date_filter_clause(time_col: tuple[str, str], filter_str: str) -> str | None:
    table, col = time_col
    f = filter_str
    if f.startswith("last_"):
        m = re.match(r"last_(\d+)_(day|week|month|quarter|year)", f)
        if m:
            n, unit = int(m.group(1)), m.group(2).upper()
            return f"\"{table}\".\"{col}\" >= CURRENT_DATE - INTERVAL '{n} {unit}'"
    if f.startswith("last_") and not re.search(r"\d+", f):
        unit = f.replace("last_", "").upper()
        return f"\"{table}\".\"{col}\" >= DATE_TRUNC('{unit}', CURRENT_DATE) - INTERVAL '1 {unit}' AND \"{table}\".\"{col}\" < DATE_TRUNC('{unit}', CURRENT_DATE)"
    if f.startswith("this_"):
        unit = f.replace("this_", "").upper()
        return f"\"{table}\".\"{col}\" >= DATE_TRUNC('{unit}', CURRENT_DATE)"
    return None


def _find_time_col(schema: dict[str, TableSchema], prefer_table: str | None = None) -> tuple[str, str] | None:
    tables = {prefer_table: schema[prefer_table]} if prefer_table in schema else schema
    for tname, t in tables.items():
        for col in t.columns:
            if col.kind == "temporal":
                return (tname, col.name)
    # fallback: look anywhere
    for tname, table in schema.items():
        for col in table.columns:
            if col.kind == "temporal":
                return (tname, col.name)
    return None


def generate_sql(question: str, intent: ParsedIntent, schema: dict[str, TableSchema], dialect: str = "duckdb") -> list[str]:
    """Returns a list of SQL statements (>=1). For compare intents, returns 3."""
    table = intent.table or next(iter(schema), None)
    if table is None:
        return ["SELECT 1;"]
    t = schema[table]
    measure_col = intent.target_column or next((c.name for c in t.columns if c.kind == "numeric"), None)
    use_count = measure_col is None

    time_col = _find_time_col(schema, prefer_table=table)
    where = ""
    if intent.date_filter and time_col:
        cl = _date_filter_clause(time_col, intent.date_filter)
        if cl:
            where = f" WHERE {cl}"

    statements: list[str] = []

    if intent.compare:
        # produce SQL that returns current and prior in one pass using CASE WHEN on time
        if time_col:
            tt, tc = time_col
            # current unit and prior unit using DATE_TRUNC
            unit = re.match(r"(?:last|this)_(\w+)", intent.date_filter).group(1).upper() if intent.date_filter else "MONTH"
            dim_clause = ""
            group_clause = ""
            if intent.dimension:
                if intent.dimension.startswith("time:"):
                    pt = intent.dimension.split(":")
                    dim_table, dim_col = pt[0], pt[1]
                    dim_expr = _trunc_expr(intent.dimension, pt[3] if len(pt) > 3 else unit.lower())
                    dim_clause = f", {dim_expr} AS dim"
                    group_clause = f" GROUP BY {dim_expr}"
                else:
                    dt, dc = intent.dimension.split(".")
                    if dt == table:
                        in_table = table
                        # join path check: if dimension table differs and FK exists, join it
                        statements = _compare_with_join(schema, intent, table, measure_col, tt, tc, unit)
                        return statements
                    else:
                        dim_clause = f', "{dt}"."{dc}" AS dim'
                        # join the dimension table via FK if known
                        statements = _compare_with_join(schema, intent, table, measure_col, tt, tc, unit)
                        return statements
            agg_expr = "COUNT(*) AS measure" if use_count else f'SUM("{table}"."{measure_col}") AS measure'
            base = f'SELECT {agg_expr}{dim_clause} FROM "{table}"'
            cur = f'{base} WHERE DATE_TRUNC(\'{unit}\', "{tt}"."{tc}") = DATE_TRUNC(\'{unit}\', CURRENT_DATE)'
            prev = f'{base} WHERE DATE_TRUNC(\'{unit}\', "{tt}"."{tc}") = DATE_TRUNC(\'{unit}\', CURRENT_DATE) - INTERVAL \'1 {unit}\''
            if group_clause:
                cur += group_clause
                prev += group_clause
            statements = [prev, cur]
        return statements

    # non-compare
    select_dims: list[str] = []
    group_dims: list[str] = []
    join_clause = ""
    if intent.dimension:
        if intent.dimension.startswith("time:"):
            parts = intent.dimension.split(":")
            grain = parts[3] if len(parts) > 3 else "month"
            expr = _trunc_expr(intent.dimension, grain)
            select_dims.append(f'{expr} AS {grain}')
            group_dims.append(expr)
        else:
            dt, dc = intent.dimension.split(".")
            if dt != table:
                # join via FK if available
                fk = next((c for c in t.columns if c.is_fk and c.fk_ref_table == dt), None)
                if fk:
                    join_clause = f' LEFT JOIN "{dt}" ON "{table}"."{fk.name}" = "{dt}"."id"'
                    select_dims.append(f'"{dt}"."{dc}" AS {dc}')
                    group_dims.append(f'"{dt}"."{dc}"')
                else:
                    select_dims.append(f'"{table}"."{dc}" AS {dc}')
                    group_dims.append(f'"{table}"."{dc}"')
            else:
                select_dims.append(f'"{table}"."{dc}" AS {dc}')
                group_dims.append(f'"{table}"."{dc}"')

    if use_count:
        agg_str = "COUNT(*) AS count"
    else:
        agg_str = f'SUM("{table}"."{measure_col}") AS {measure_col}'
    if not use_count and intent.measure and "_id" in (intent.measure or "").lower():
        use_count = True
        agg_str = "COUNT(*) AS count"
    sel = ", ".join(select_dims + [agg_str])
    group_by = f" GROUP BY {', '.join(group_dims)}" if group_dims else ""
    order_by = ""
    if intent.top_n:
        order_col = agg_str.split(" AS ")[1]
        assert order_col  # for type checker
        order_by = f" ORDER BY {order_col} DESC LIMIT {intent.top_n}"
    elif any("AS " in s for s in select_dims) and group_dims:
        order_by = " ORDER BY 1"
    sql = f'SELECT {sel} FROM "{table}"{join_clause}{where}{group_by}{order_by}'
    return [sql]


def _compare_with_join(schema, intent, table, measure_col, tt, tc, unit):
    """Generate two joined compare statements when dimension is in another table."""
    dt, dc = (intent.dimension.split(".") if not intent.dimension.startswith("time:") else (table, "x"))
    t = schema[table]
    join_clause = ""
    if dt != table:
        fk = next((c for c in t.columns if c.is_fk and c.fk_ref_table == dt), None)
        if fk:
            join_clause = f' LEFT JOIN "{dt}" ON "{table}"."{fk.name}" = "{dt}"."id"'
    dim_sel = f'"{dt}"."{dc}" AS dim' if not dt == table else f'"{table}"."{dc}" AS dim'
    agg_expr = "COUNT(*) AS measure" if measure_col is None else f'SUM("{table}"."{measure_col}") AS measure'
    base = f'SELECT {dim_sel}, {agg_expr} FROM "{table}"{join_clause}'
    cur = f"{base} WHERE DATE_TRUNC('{unit}', \"{tt}\".\"{tc}\") = DATE_TRUNC('{unit}', CURRENT_DATE) GROUP BY \"{dt}\".\"{dc}\""
    prev = f"{base} WHERE DATE_TRUNC('{unit}', \"{tt}\".\"{tc}\") = DATE_TRUNC('{unit}', CURRENT_DATE) - INTERVAL '1 {unit}' GROUP BY \"{dt}\".\"{dc}\""
    return [prev, cur]


# ---------- validator ----------

FORBIDDEN = ("DROP", "DELETE", "UPDATE", "INSERT", "TRUNCATE", "ALTER", "GRANT", "REVOKE", "MERGE", "CALL", "SET ")


def validate_sql(sql: str, schema: dict[str, TableSchema]) -> list[str]:
    """Return a list of problems (empty list means OK)."""
    problems: list[str] = []
    su = sql.upper()
    # read-only guard
    for kw in FORBIDDEN:
        if re.search(rf"\b{kw}\b", su):
            problems.append(f"Disallowed operation: {kw}.")
    # must start with SELECT or WITH
    stripped = sql.lstrip()
    if not (stripped.upper().startswith("SELECT") or stripped.upper().startswith("WITH")):
        problems.append("Only SELECT/WITH statements are allowed.")
    if not stripped.rstrip(";").strip().endswith((")", ") ")) and not stripped.rstrip().endswith(";"):
        pass
    # must reference an existing table
    tables = set(schema.keys())
    found_tables = set(re.findall(r'"([^"]+)"', sql))
    known_missing = [t for t in found_tables if t not in tables]
    if not known_missing:
        known_missing = [t for t in found_tables if not any(t in tables for _ in [0])]
    return problems


# ---------- self-correction ----------

def _maybe_fix_error(sql: str, error: str, schema) -> str | None:
    """Very small heuristic fixer."""
    mmsg = error.lower()
    if "no such column" in mmsg or "column" in mmsg and "does not exist" in mmsg:
        m = re.search(r"column(?: named)?[:\s]+(\"?)([A-Za-z_][A-Za-z0-9_]*)\1", error, re.I)
        if m:
            bad = m.group(2)
            # drop any column refs that don't exist in the schema
            valid_cols = set()
            for _, t in schema.items():
                for c in t.columns:
                    valid_cols.add(c.name.lower())
            # crude: strip the offending column select clause
            new = re.sub(rf'[^,]*"{bad}"\s+AS\s+\w+', "", sql, flags=re.I)
            if new != sql:
                return new
    return None


# ---------- main entrypoint ----------

def run_pipeline(question: str, connector: BaseConnector, schema: dict[str, TableSchema]) -> AnalysisResult:
    intent = detect_intent(question, schema)
    plan = build_plan(question, intent)
    sqls = generate_sql(question, intent, schema)
    # validate all
    for sql in sqls:
        problems = validate_sql(sql, schema)
        if problems:
            return AnalysisResult(intent=intent, plan=plan, steps=[], final_rows=[], sql="; ".join(sqls),
                                  execution_time=0.0, success=False, error="; ".join(problems))

    steps: list[StepResult] = []
    retries = 0
    for i, sql in enumerate(sqls):
        attempt_sql = sql
        local_retries = 0
        last_err = None
        while local_retries <= 1:
            try:
                rows, dt = connector.execute(attempt_sql)
                steps.append(StepResult(step_id=i + 1, description=plan[i]["action"] if i < len(plan) else "execute",
                                        sql=attempt_sql, rows=rows, execution_time=dt))
                last_err = None
                break
            except Exception as e:  # noqa: BLE001
                last_err = str(e)
                fixed = _maybe_fix_error(attempt_sql, last_err, schema)
                local_retries += 1
                retries += 1
                if fixed:
                    attempt_sql = fixed
                    continue
                break
        if last_err:
            steps.append(StepResult(step_id=i + 1, description="execute", sql=attempt_sql, error=last_err, execution_time=0.0))
            return AnalysisResult(intent=intent, plan=plan, steps=steps, final_rows=[], sql="; ".join(sqls),
                                  execution_time=sum(s.execution_time for s in steps), retries=retries,
                                  success=False, error="; ".join(s.error or "" for s in steps))

    final_rows = steps[-1].rows if steps else []
    total_time = sum(s.execution_time for s in steps)

    # Merge compare-query results into a single grouped dataset.
    if intent.compare and len(steps) >= 2:
        prev_rows = steps[0].rows or []
        cur_rows = steps[1].rows or []
        # find the dimension column (we used `dim` alias for categorical, or
        # the temporal trunc alias like `month`).
        dim_col = None
        if cur_rows:
            dim_col = next((k for k in cur_rows[0] if k not in ("measure",)), None)
        if dim_col is None:
            dim_col = next((k for k in (cur_rows[0] if cur_rows else {})
                            if k != "measure"), None)
        measure_key = "measure" if (cur_rows and "measure" in cur_rows[0]) else None
        if dim_col is not None and measure_key:
            prev_map = {r.get(dim_col): r.get(measure_key, 0) for r in prev_rows}
            cur_map = {r.get(dim_col): r.get(measure_key, 0) for r in cur_rows}
            all_keys = list(dict.fromkeys(list(prev_map.keys()) + list(cur_map.keys())))
            final_rows = []
            for k in all_keys:
                p = prev_map.get(k, 0) or 0
                c_ = cur_map.get(k, 0) or 0
                delta = (c_ - p)
                pct = (delta / p * 100.0) if p else None
                final_rows.append({
                    dim_col: k, "previous": p, "current": c_,
                    "delta": delta,
                    "percent_change": round(pct, 2) if pct is not None else None,
                })
            # add merge + delta steps to the timeline
            steps.append(StepResult(
                step_id=len(steps) + 1, description="Merge & delta",
                rows=final_rows, execution_time=0.0,
                sql="-- merged in application code",
            ))

    return AnalysisResult(intent=intent, plan=plan, steps=steps, final_rows=final_rows,
                          sql="; ".join(sqls), execution_time=total_time, retries=retries, success=True)
